//
//  Constants.swift
//  ogp
//
//  Created by Alex Young on 4/20/26.
//

let SectionNames = [
    "101": "General Regulations",
    "102": "Reports and Reporting Procedures",
    "103": "Disciplinary Action",
    "104": "Personnel Procedures",
    "105": "Emergency Response Plan",
    "106": "Operations",
    "107": "Vehicles",
    "108": "Equipment",
    "109": "Communications",
    "110": "Human Resources",
    "111": "Facilities",
    "112": "Incident Command System",
    "113": "Legal",
    "115": "Hospitals",
    "120": "Time and Leave Procedures",
    "125": "Health and Safety Procedures",
    "130": "Requests Misc. Procedures",
    "200": "Voluntary Hospital Procedures",
]

let acronyms = [
    "8000XE",
    "ALS",
    "APR",
    "APX",
    "ARC",
    "BHEARD",
    "BLS",
    "CD-19",
    "CPC",
    "DAREMS",
    "DOH",
    "DNR",
    "EEO",
    "EMD",
    "EMS",
    "EMT",
    "ePCR",
    "FDOC",
    "FDNY",
    "FOC",
    "FOC-1",
    "GF-10-EX",
    "GNY",
    "HBOT",
    "HLU",
    "ICE",
    "ICS",
    "ID",
    "LVAD",
    "MCI",
    "MD-14F",
    "MOLST",
    "MRx",
    "MSA",
    "NYS",
    "OMA",
    "PCRs",
    "PFD",
    "PSA",
    "PCI",
    "RAC",
    "RAD-57",
    "REMAC",
    "RMA",
    "ROSC",
    "SAFE",
    "ST",
    "STAT",
    "USPS",
    "WMD",
    "WTC",
]
